### PR TITLE
add wsrep view from old version

### PR DESCRIPTION
**Pull request by jayjanssen**
```
         Cluster  Node    Outbound      Inbound       FlowC     Conflct Gcache     Appl
    time P cnf  #  i stat msgs data que msgs data que pause snt lcf bfa   ist  idx  %ef
20:23:13 P   1  1  0 Sync    2 424b   0    2 148b   0   0ns   0   0   0     1    1  50%
20:23:14 P   1  1  0 Sync    0   0b   0    0   0b   0   0ns   0   0   0     1    1  50%
20:23:15 P   1  1  0 Sync    0   0b   0    0   0b   0   0ns   0   0   0     1    1  50%
20:23:16 P   1  1  0 Sync    0   0b   0    0   0b   0   0ns   0   0   0     1    1  50%
20:23:17 P   1  1  0 Sync    0   0b   0    0   0b   0   0ns   0   0   0     1    1  50%
20:23:18 P   1  1  0 Sync    0   0b   0    0   0b   0   0ns   0   0   0     1    1  50%
20:23:19 P   1  1  0 Sync    0   0b   0    0   0b   0   0ns   0   0   0     1    1  50%
20:23:20 P   1  1  0 Sync    0   0b   0    0   0b   0   0ns   0   0   0     1    1  50%
20:23:21 P   1  1  0 Sync    0   0b   0    0   0b   0   0ns   0   0   0     1    1  50%
20:23:22 P   1  1  0 Sync    0   0b   0    0   0b   0   0ns   0   0   0     1    1  50%
20:23:23 P   1  1  0 Sync    0   0b   0    0   0b   0   0ns   0   0   0     1    1  50%
20:23:24 P   1  1  0 Sync    0   0b   0    0   0b   0   0ns   0   0   0     1    1  50%
20:23:25 P   1  1  0 Sync    0   0b   0    0   0b   0   0ns   0   0   0     1    1  50%
20:23:26 P   1  1  0 Sync    0   0b   0    0   0b   0   0ns   0   0   0     1    1  50%
20:23:27 P   1  1  0 Sync    0   0b   0    0   0b   0   0ns   0   0   0     1    1  50%
```

### CODE REVIEW

**Comment by jayjanssen** [comment]
Missing:
* Extra header with cluster & node names `galera / node01 (idx: 1) / Galera 25.3.35(r545d0bf)`
* `laten` column
I may come back and tinker a bit more here.

**Comment by b2cc** [comment]
Hello @jayjanssen !

Thanks for considering and adding this back! I built `myq_status` from the PR branch, but when I run it I get an error:

```
~# ./myq_status -u root -S /var/lib/mysql/mysql.sock wsrep
         Cluster  Node    Outbound      Inbound       FlowC     Conflct Gcache     Appl
    time P cnf  #  i stat msgs data que msgs data que pause snt lcf bfa   ist  idx  %ef
panic: runtime error: slice bounds out of range [:4] with length 1

goroutine 1 [running]:
github.com/jayjanssen/myq-tools2/viewer.SwitchCol.GetData({{{0xc0001bd214, 0x5}, {0xc00014a948, 0x12}, {0xc0001bd244, 0x6}, 0x4, {0x0, 0x0, 0x0}}, ...}, ...)
        /home/b2c/git/myq-tools/viewer/col_switch.go:26 +0x1b8
github.com/jayjanssen/myq-tools2/viewer.GroupCol.GetData.func1({0x74abf0?, 0xc00020c700?})
        /home/b2c/git/myq-tools/viewer/col_group.go:45 +0x32
github.com/jayjanssen/myq-tools2/viewer.pushColOutputUp({0xc000149a20, 0x2, 0xc00015d8e8?}, 0xc00015d8c0)
        /home/b2c/git/myq-tools/viewer/utils.go:124 +0xb9
github.com/jayjanssen/myq-tools2/viewer.GroupCol.GetData({{{0xc0001bd15c, 0x4}, {0xc00014a918, 0x15}, {0x0, 0x0}, 0x0, {0x0, 0x0, 0x0}}, ...}, ...)
        /home/b2c/git/myq-tools/viewer/col_group.go:47 +0x6b
github.com/jayjanssen/myq-tools2/viewer.View.GetData.func1({0x74a970?, 0xc00020f810?})
        /home/b2c/git/myq-tools/viewer/view.go:83 +0x32
github.com/jayjanssen/myq-tools2/viewer.pushColOutputUp({0xc0001ee800, 0x9, 0xc00015db38?}, 0xc00015db38)
        /home/b2c/git/myq-tools/viewer/utils.go:124 +0xb9
github.com/jayjanssen/myq-tools2/viewer.View.GetData({{{{0xc0001bcfb0, 0x5}, {0xc00014a900, 0x17}, {0x0, 0x0}, 0x0, {0x0, 0x0, 0x0}}, ...}, ...}, ...)
        /home/b2c/git/myq-tools/viewer/view.go:82 +0x1aa
main.main()
        /home/b2c/git/myq-tools/cli/myq-status/main.go:187 +0xdc2
```

Other commands like `innodb` etc. work, so it must be something specific with `wsrep`.

**Comment by jayjanssen** [comment]
hey @b2cc , give the latest pushes another try.  That's what I get for not writing tests.

**Comment by jayjanssen** [comment]
I think it's just an authentication issue:

```
 ./myq-status -u test -h 127.0.0.1 wsrep
         Cluster  Node    Outbound      Inbound       FlowC     Conflct Gcache     Appl
    time P cnf  #  i stat msgs data que msgs data que pause snt lcf bfa   ist  idx  %ef
13:07:30 P   1  1  0 Sync    2 448b   0    2 148b   0   0ns   0   0   0     1    1  50%
13:07:31 P   1  1  0 Sync    0   0b   0    0   0b   0   0ns   0   0   0     1    1  50%

./myq-status -u not_a_user -h 127.0.0.1 wsrep
         Cluster  Node    Outbound      Inbound       FlowC     Conflct Gcache     Appl
    time P cnf  #  i stat msgs data que msgs data que pause snt lcf bfa   ist  idx  %ef
13:09:24 -   -  -  -    -    -    -   -    -    -   -     -   -   -   -     -    -    -
13:09:25 -   -  -  -    -    -    -   -    -    -   -     -   -   -   -     -    -    -
13:09:26 -   -  -  -    -    -    -   -    -    -   -     -   -   -   -     -    -    -
```

I'll see about throwing a better error if the initial DB connection can't be made

**Comment by jayjanssen** [comment]
Looks better now:
```
~/Development/myq-tools/cli/myq-status 24-re-add-view-for-galera-statistics ./myq-status -u not_a_user -h 127.0.0.1 wsrep
Error 1045: Access denied for user 'not_a_user'@'_gateway' (using password: NO)

~/Development/myq-tools/cli/myq-status 24-re-add-view-for-galera-statistics ./myq-status -u test -h 127.0.0.1 wsrep
         Cluster  Node    Outbound      Inbound       FlowC     Conflct Gcache     Appl
    time P cnf  #  i stat msgs data que msgs data que pause snt lcf bfa   ist  idx  %ef
13:54:00 P   1  1  0 Sync    2 448b   0    2 148b   0   0ns   0   0   0     1    1  50%
13:54:01 P   1  1  0 Sync    0   0b   0    0   0b   0   0ns   0   0   0     1    1  50%
13:54:02 P   1  1  0 Sync    0   0b   0    0   0b   0   0ns   0   0   0     1    1  50%
13:54:03 P   1  1  0 Sync    0   0b   0    0   0b   0   0ns   0   0   0     1    1  50%
```

**Comment by b2cc** [comment]
Ok, definitely an authentication issue. We usually connect by socket, and not by host/port, where we usually disable `root` access for security reasons.

When I connect via socket I now get:

```
~# ./myq_status -socket /var/lib/mysql/mysql.sock -user root -password ****** wsrep
dial tcp 127.0.0.1:3306: connect: connection refused
```
which is weird since I didn't specify any host or port options.

If I use the `mysql` CLI it works:
```
~# mysql -uroot -S /var/lib/mysql/mysql.sock -uroot -p******
Enter password: 

Server version: 8.0.28-19.1 Percona XtraDB Cluster (GPL), Release rel19, Revision f544540, WSREP version 26.4.3
mysql>
```

Am I missing something?

**Comment by jayjanssen** [comment]
Ok, there's just some issue with parsing the cli.  The tool also attempts to use any defaults files you may have lying around.

I added a quick patch to this branch that should output the config DSN that the tool is sending to the mysql driver.  Can you share the output from that?

**Comment by b2cc** [comment]
Interesting, that may partially explain what is happening. I was testing from the home of the mysql instance where we have a `.my.cnf` with the configuration and credential information, which `myq-status` seems to parse.

If I call it like before I get:
```
user@server ~# ./myq_status -socket /var/lib/mysql/mysql.sock -user root -password ****** wsrep
root:******@tcp(127.0.0.1:3306)/
dial tcp 127.0.0.1:3306: connect: connection refused
```

If I call it without any arguments, it still seems to finds the password from the `.my.cnf` file:
```
user@server ~# ./myq_status wsrep
root:******@tcp(127.0.0.1:3306)/
dial tcp 127.0.0.1:3306: connect: connection refused
```

If I call it from the root user it seems it can't find any credentials (we have no `/etc/my.cnf` or other files it could parse for that matter) and just correctly errors out:
```
root@server ~# ./myq_status-socket /var/lib/mysql_instances/financing-platform-live-33992/run/mysql.financing-platform-live-33992.sock -user root wsrep
root@tcp(127.0.0.1:3306)/
dial tcp 127.0.0.1:3306: connect: connection refused
```

So it seems to just ignore the socket option and always go for a IP/port connect.

**Comment by jayjanssen** [comment]
Ok, I think I know what's happening.  My code defaults the host and port variables and doesn't seem to handle that with the combination of -socket properly.    

```
./myq_status -socket /var/lib/mysql/mysql.sock -host "" -port "" -user root -password ****** wsrep
```

I'll work on fixing this more properly soon.

**Comment by b2cc** [comment]
Tried it, but no dice:

```
user@server ~# ./myq_status -socket /var/lib/mysql/mysql.sock -host "" -port "" -user root -password ****** wsrep
root:******@tcp(127.0.0.1:3306)/
dial tcp 127.0.0.1:3306: connect: connection refused
```

**Comment by jayjanssen** [comment]
Alright, give it another whirl.  I reworked the cli arg parsing

**Pull request merged**
